$(document).ready(function() {	
	//konfig dialog button
	$("#kosong1").click(function(){
		$("#viewkosong1").modal('show');
	});
	$("#kosong2").click(function(){
		$("#viewkosong2").modal('show');
	});
	$("#kosong3").click(function(){
		$("#viewkosong3").modal('show');
	});
	$("#editprofil").click(function(){
		$("#vieweditprofil").modal('show');
	});
	$("#infosayhid").click(function(){
		$("#viewinfosayhid").modal('show');
	});
	$("#infodaging").click(function(){
		$("#viewinfodaging").modal('show');
	});
	$("#infomakjad").click(function(){
		$("#viewinfomakjad").modal('show');
	});
	$("#infominuman").click(function(){
		$("#viewinfominuman").modal('show');
	});
	$("#infozik").click(function(){
		$("#viewinfozik").modal('show');
	});
	$("#infowan").click(function(){
		$("#viewinfowan").modal('show');
	});
	$("#infojar").click(function(){
		$("#viewinfojar").modal('show');
	});
	
	$("#belitomat").click(function(){
		$("#pembeliantomat").modal('show');
	});
	$("#beliketimun").click(function(){
		$("#pembelianketimun").modal('show');
	});
	$("#belikentang").click(function(){
		$("#pembeliankentang").modal('show');
	});
	$("#belilabu").click(function(){
		$("#pembelianlabu").modal('show');
	});
});

